### PR TITLE
fix: upgrade `@vue/language-core`

### PR DESCRIPTION
**Pull request by antfu**
There was a breaking change in `@vue/language-core` v2.1, Twoslsash v0.2.10 locked it in patch range in https://github.com/twoslashes/twoslash/commit/2ce57ba82a5272755a7d762e781c5b5af13856cf as an temporary workaround.

This PR is trying to upgrade the language tool but got runtime errors.

/cc @johnsoncodehk, do you have any clue how to fix this? Thank you

### CODE REVIEW

**Comment by KazariEX** [comment]
https://github.com/twoslashes/twoslash/blob/8226ef80abefcc243568f73d32eeff0e025e1677/packages/twoslash-vue/src/index.ts#L146

Change the second parameter to `2`, and I will fix the rest in `@vue/language-core`.

**Comment by zhiyuanzmj** [comment]
https://github.com/twoslashes/twoslash/pull/53

**Comment by antfu** [comment]
Thanks @zhiyuanzmj @KazariEX!

**Comment by sxzz** [comment]
@antfu Could you please release a new version for it?

**Pull request merged**
